[tool.poetry]
name = "ms-sbom-export"
version = "0.1.0"
description = ""
authors = ["Steve Taylor <steve@deployhub.com>"]
license = "Apache-2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.115.12"
psycopg2-binary = "2.9.10"
pydantic = "2.11.1"
sqlalchemy = "2.0.40"
uvicorn = "0.34.0"
requests = "2.32.3"
numpy = "2.2.4"
pandas = "2.2.3"
weasyprint = "65.0"
starlette = "0.46.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
