[tool.poetry]
name = "ms-sbom-export"
version = "0.1.0"
description = ""
authors = ["Steve Taylor <steve@deployhub.com>"]
license = "Apache-2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.115.6"
psycopg2-binary = "2.9.10"
pydantic = "2.10.3"
sqlalchemy = "2.0.36"
uvicorn = "0.32.1"
requests = "2.32.3"
numpy = "2.2.0"
pandas = "2.2.3"
weasyprint = "63.1"
starlette = "0.41.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
