[tool.poetry]
name = "ms-sbom-export"
version = "0.1.0"
description = ""
authors = ["Steve Taylor <steve@deployhub.com>"]
license = "Apache-2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.115.5"
psycopg2-binary = "2.9.10"
pydantic = "2.9.2"
sqlalchemy = "2.0.36"
uvicorn = "0.32.0"
requests = "2.32.3"
numpy = "2.1.3"
pandas = "2.2.3"
weasyprint = "63.0"
starlette = "0.41.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
